/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-03 16:47:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.Customer;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1727716940364L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1727718915179L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Model.Customer");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en-US\" dir=\"ltr\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ===============================================-->\r\n");
      out.write("        <!--    Document Title-->\r\n");
      out.write("        <!-- ===============================================-->\r\n");
      out.write("        <title>watch | Landing, Ecommerce &amp; Business Templatee</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ===============================================-->\r\n");
      out.write("        <!--    Favicons-->\r\n");
      out.write("        <!-- ===============================================-->\r\n");
      out.write("        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/img/favicons/apple-touch-icon.png\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/img/favicons/favicon-32x32.png\">\r\n");
      out.write("        <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/img/favicons/favicon-16x16.png\">\r\n");
      out.write("        <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicons/favicon.ico\">\r\n");
      out.write("        <link rel=\"manifest\" href=\"assets/img/favicons/manifest.json\">\r\n");
      out.write("        <meta name=\"msapplication-TileImage\" content=\"assets/img/favicons/mstile-150x150.png\">\r\n");
      out.write("        <meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link href=\"assets/css/theme.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ===============================================-->\r\n");
      out.write("<!--    Main Content-->\r\n");
      out.write("<!-- ===============================================-->\r\n");
      out.write("<main class=\"main\" id=\"top\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lora:400,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Cabin:400,500,600,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Css Styles -->\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"assets/img/favicons/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"assets/img/favicons/favicon-32x32.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"assets/img/favicons/favicon-16x16.png\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"assets/img/favicons/favicon.ico\">\r\n");
      out.write("<link rel=\"manifest\" href=\"assets/img/favicons/manifest.json\">\r\n");
      out.write("<meta name=\"msapplication-TileImage\" content=\"assets/img/favicons/mstile-150x150.png\">\r\n");
      out.write("<meta name=\"theme-color\" content=\"#ffffff\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"assets/css/theme.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .avatar-navbar {\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-dropdown {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        background-color: #f9f9f9;\r\n");
      out.write("        min-width: 160px;\r\n");
      out.write("        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-dropdown ul {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-dropdown ul li {\r\n");
      out.write("        padding: 12px 16px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        display: block;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-dropdown ul li:hover {\r\n");
      out.write("        background-color: #f1f1f1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-dropdown ul li a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-dropdown ul li a:hover {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

    Customer account = (Customer) session.getAttribute("account");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light fixed-top py-3 d-block\" data-navbar-on-scroll=\"data-navbar-on-scroll\">\r\n");
      out.write("    <div class=\"container\"><a class=\"navbar-brand d-inline-flex\" href=\"/\"><span class=\"text-light fs-2 fw-bold ms-2\">Watch</span></a>\r\n");
      out.write("        <button class=\"navbar-toggler collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("                <li class=\"nav-item px-2\"><a class=\"nav-link fw-bold active\" aria-current=\"page\" href=\"/\">WATCHES</a></li>\r\n");
      out.write("                <li class=\"nav-item px-2\"><a class=\"nav-link fw-bold\" href=\"#store\">STORE</a></li>\r\n");
      out.write("                <li class=\"nav-item px-2\"><a class=\"nav-link fw-bold\" href=\"#contact\">CONTACT</a></li>\r\n");
      out.write("                <li class=\"nav-item px-2\"><a class=\"nav-link fw-bold\" href=\"#header\">REQUEST VIRTUAL</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (account == null) { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item px-2\"><a class=\"nav-link fw-bold\" href=\"login.jsp\">LOGIN</a></li>\r\n");
      out.write("                    <li class=\"nav-item px-2\"><a class=\"nav-link fw-bold\" href=\"register.jsp\">REGISTER</a></li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item px-2\"><img src=\"");
      out.print( account.getAvatar() );
      out.write("\" alt=\"avatar\" class=\"avatar-navbar\" id=\"avatar-navbar\"></li>\r\n");
      out.write("                    <div class=\"profile-dropdown\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"profile\">Profile</a></li>\r\n");
      out.write("                            <li><a href=\"logout\">Logout</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById(\"avatar-navbar\").addEventListener(\"click\", function () {\r\n");
      out.write("        document.getElementsByClassName(\"profile-dropdown\")[0].style.display = \"block\";\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener(\"click\", function (e) {\r\n");
      out.write("        if (!e.target.matches('.avatar-navbar')) {\r\n");
      out.write("            var dropdowns = document.getElementsByClassName(\"profile-dropdown\");\r\n");
      out.write("            for (var d of dropdowns) {\r\n");
      out.write("                d.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"vendors/@popperjs/popper.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/is/is.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/feather-icons/feather.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    feather.replace();\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"assets/js/theme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;700&amp;display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <section class=\"py-0\" id=\"header\">\r\n");
      out.write("                <div class=\"bg-holder\" style=\"background-image:url(assets/img/gallery/header-bg.png);background-position:right top;background-size:contain;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.bg-holder-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                        <div class=\"row align-items-center min-vh-75 min-vh-xl-100\">\r\n");
      out.write("                                <div class=\"col-md-8 col-lg-6 text-md-start text-center\">\r\n");
      out.write("                                        <h1 class=\"display-1 lh-sm text-uppercase text-light\">Custom Watches For <br class=\"d-none d-xxl-block\" /> Any Occasion</h1>\r\n");
      out.write("                                        <div class=\"pt-4\"><a class=\"btn btn-sm btn-outline-primary me-3\" href=\"#\">DESIGN &amp; ORDER</a><a class=\"btn btn-sm btn-outline-primary\" href=\"#\">REQUEST VIRTUAL</a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"bg-black py-8 pt-0\" id=\"store\">\r\n");
      out.write("                <div class=\"bg-holder\" style=\"background-image:url(assets/img/gallery/store-bg.png);background-position:left bottom;background-size:contain;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.bg-holder-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container-lg\">\r\n");
      out.write("                        <div class=\"row flex-center\">\r\n");
      out.write("                                <div class=\"col-6 order-md-0 text-center text-md-start\"></div>\r\n");
      out.write("                                <div class=\"col-sm-10 col-md-6 col-lg-6 text-center text-md-start\">\r\n");
      out.write("                                        <div class=\"col-4 position-relative ms-auto py-5\"><a class=\"carousel-control-prev carousel-icon z-index-2\" href=\"#carouselExampleFade\" role=\"button\" data-bs-slide=\"prev\"><span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span><span class=\"visually-hidden\">Previous</span></a><a class=\"carousel-control-next carousel-icon z-index-2\" href=\"#carouselExampleFade\" role=\"button\" data-bs-slide=\"next\"><span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span><span class=\"visually-hidden\">Next</span></a></div>\r\n");
      out.write("                                        <div class=\"carousel slide carousel-fade\" id=\"carouselExampleFade\" data-bs-ride=\"carousel\">\r\n");
      out.write("                                                <div class=\"carousel-inner\">\r\n");
      out.write("                                                        <div class=\"carousel-item active\">\r\n");
      out.write("                                                                <div class=\"row h-100\">\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                                <h5 class=\"fs-3 fs-lg-5 lh-sm text-uppercase\">Our store</h5>\r\n");
      out.write("                                                                                <p class=\"my-4 pe-xl-5\">Memphis clinched a spot in the play-in tournament with the victory, but the fight for seeding continues. The race for the No. 8 spot in the West -- and the safety net of having to win just one of two games to make the playoffs -- could come down to the regular seasons final day, when Memphis and Golden State meet. The good thing for the Grizzlies is they dont have to leave home until that matchup as they have games against Dallas and two against Sacramento before the finale.</p>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"carousel-item\">\r\n");
      out.write("                                                                <div class=\"row h-100\">\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                                <h5 class=\"fs-3 fs-lg-5 lh-sm text-uppercase\">Our store</h5>\r\n");
      out.write("                                                                                <p class=\"my-4 pe-xl-5\">Memphis clinched a spot in the play-in tournament with the victory, but the fight for seeding continues. The race for the No. 8 spot in the West -- and the safety net of having to win just one of two games to make the playoffs -- could come down to the regular seasons final day, when Memphis and Golden State meet. The good thing for the Grizzlies is they dont have to leave home until that matchup as they have games against Dallas and two against Sacramento before the finale.</p>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"carousel-item\">\r\n");
      out.write("                                                                <div class=\"row h-100\">\r\n");
      out.write("                                                                        <div class=\"col-12\">\r\n");
      out.write("                                                                                <h5 class=\"fs-3 fs-lg-5 lh-sm text-uppercase\">Our store</h5>\r\n");
      out.write("                                                                                <p class=\"my-4 pe-xl-5\">Memphis clinched a spot in the play-in tournament with the victory, but the fight for seeding continues. The race for the No. 8 spot in the West -- and the safety net of having to win just one of two games to make the playoffs -- could come down to the regular seasons final day, when Memphis and Golden State meet. The good thing for the Grizzlies is they dont have to leave home until that matchup as they have games against Dallas and two against Sacramento before the finale.</p>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"py-0 pb-6\" id=\"collections\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                        <div class=\"row h-100\">\r\n");
      out.write("                                <div class=\"col-lg-7 mt-7\">\r\n");
      out.write("                                        <h5 class=\"fs-3 fs-lg-5 lh-sm mb-0 text-uppercase\">Collections</h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                        <nav>\r\n");
      out.write("                                                <div class=\"nav nav-tabs watch-tabs mb-4 justify-content-end\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("                                                        <button class=\"nav-link active\" id=\"nav-latest-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#nav-latest\" type=\"button\" role=\"tab\" aria-controls=\"nav-latest\" aria-selected=\"true\">LATEST </button>\r\n");
      out.write("                                                        <button class=\"nav-link\" id=\"nav-popular-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#nav-popular\" type=\"button\" role=\"tab\" aria-controls=\"nav-popular\" aria-selected=\"false\">POPULAR</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                        </nav>\r\n");
      out.write("                                        <div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("                                                <div class=\"tab-pane fade show active\" id=\"nav-latest\" role=\"tabpanel\" aria-labelledby=\"nav-latest-tab\">\r\n");
      out.write("                                                        <div class=\"carousel slide\" id=\"carouselLatest\" data-bs-ride=\"carousel\">\r\n");
      out.write("                                                                <div class=\"carousel-inner\">\r\n");
      out.write("                                                                        <div class=\"carousel-item active\" data-bs-interval=\"10000\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"carousel-item\" data-bs-interval=\"5000\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"carousel-item\" data-bs-interval=\"3000\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"carousel-item\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"row\">\r\n");
      out.write("                                                                                <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselLatest\" data-bs-slide=\"prev\"><span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span><span class=\"visually-hidden\">Previous</span></button>\r\n");
      out.write("                                                                                <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselLatest\" data-bs-slide=\"next\"><span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span><span class=\"visually-hidden\">Next </span></button>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"tab-pane fade\" id=\"nav-popular\" role=\"tabpanel\" aria-labelledby=\"nav-popular-tab\">\r\n");
      out.write("                                                        <div class=\"carousel slide\" id=\"carouselPopular\" data-bs-ride=\"carousel\">\r\n");
      out.write("                                                                <div class=\"carousel-inner\">\r\n");
      out.write("                                                                        <div class=\"carousel-item active\" data-bs-interval=\"10000\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"carousel-item\" data-bs-interval=\"5000\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"carousel-item\" data-bs-interval=\"3000\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"carousel-item\">\r\n");
      out.write("                                                                                <div class=\"row h-100 align-items-center\">\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-2.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$650.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ADRIATICA ADR</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-3.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$126.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">SEIKO SNZGO7K1</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                        <div class=\"col-sm-6 col-md-4 mb-3 mb-md-0\">\r\n");
      out.write("                                                                                                <div class=\"card bg-black text-white p-6 pb-8\"><img class=\"card-img\" src=\"assets/img/gallery/watch-1.png\" alt=\"...\" />\r\n");
      out.write("                                                                                                        <div class=\"card-img-overlay bg-dark-gradient d-flex flex-column-reverse align-items-center\">\r\n");
      out.write("                                                                                                                <h6 class=\"text-primary\">$250.00</h6>\r\n");
      out.write("                                                                                                                <h4 class=\"text-light\">ROAMER RM 220837</h4>\r\n");
      out.write("                                                                                                        </div><a class=\"stretched-link\" href=\"#\"></a>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"row\">\r\n");
      out.write("                                                                                <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselPopular\" data-bs-slide=\"prev\"><span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span><span class=\"visually-hidden\">Previous</span></button>\r\n");
      out.write("                                                                                <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselPopular\" data-bs-slide=\"next\"><span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span><span class=\"visually-hidden\">Next </span></button>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ============================================-->\r\n");
      out.write("        <!-- <section> begin ============================-->\r\n");
      out.write("        <section class=\"py-6 bg-dark\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-sm-6 col-lg-3 mb-4 mb-lg-0 d-flex flex-center\"><img src=\"assets/img/gallery/rado.png\" alt=\"brands\" /></div>\r\n");
      out.write("                                <div class=\"col-sm-6 col-lg-3 mb-4 mb-lg-0 d-flex flex-center\"><img src=\"assets/img/gallery/swatch.png\" alt=\"brands\" /></div>\r\n");
      out.write("                                <div class=\"col-sm-6 col-lg-3 mb-4 mb-lg-0 d-flex flex-center\"><img src=\"assets/img/gallery/omega-1.png\" alt=\"brands\" /></div>\r\n");
      out.write("                                <div class=\"col-sm-6 col-lg-3 mb-4 mb-lg-0 d-flex flex-center\"><img src=\"assets/img/gallery/zenith.png\" alt=\"brands\" /></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- end of .container-->\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- <section> close ============================-->\r\n");
      out.write("        <!-- ============================================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ============================================-->\r\n");
      out.write("        <!-- <section> begin ============================-->\r\n");
      out.write("        <section id=\"testimonial\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-lg-7 mx-auto text-center my-5\">\r\n");
      out.write("                                        <h5 class=\"fs-3 fs-lg-5 lh-sm mb-0 text-uppercase\">what customers are saying</h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row flex-center h-100\">\r\n");
      out.write("                                <div class=\"col-xl-9\">\r\n");
      out.write("                                        <div class=\"carousel slide\" id=\"carouselTestimonials\" data-bs-ride=\"carousel\">\r\n");
      out.write("                                                <div class=\"carousel-inner\">\r\n");
      out.write("                                                        <div class=\"carousel-item active\" data-bs-interval=\"10000\">\r\n");
      out.write("                                                                <div class=\"row h-100 justify-content-center\">\r\n");
      out.write("                                                                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                                                                <div class=\"card h-100 shadow card-span p-3 bg-black\">\r\n");
      out.write("                                                                                        <div class=\"card-body\">\r\n");
      out.write("                                                                                                <div class=\"d-flex align-items-center\"><img class=\"img-fluid\" src=\"assets/img/gallery/smith.png\" width=\"80\" alt=\"testimonials\" />\r\n");
      out.write("                                                                                                        <div class=\"flex-1 ms-4\">\r\n");
      out.write("                                                                                                                <h6 class=\"fs-lg-1 mb-1 text-uppercase\">amanda smith</h6>\r\n");
      out.write("                                                                                                        </div>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                                <p class=\"mb-0 mt-4 fw-light lh-lg\">Nisi cumque in necessitatibus molestiae eaque excepturi ab. Laboriosam ipsam voluptatem voluptatibus labore quam nihil. Quasi occaecati quos ratione quia aut molestiae velit et.</p>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                                                                <div class=\"card h-100 shadow card-span p-3 bg-black\">\r\n");
      out.write("                                                                                        <div class=\"card-body\">\r\n");
      out.write("                                                                                                <div class=\"d-flex align-items-center\"><img class=\"img-fluid\" src=\"assets/img/gallery/sandra-willims.png\" width=\"80\" alt=\"testimonials\" />\r\n");
      out.write("                                                                                                        <div class=\"flex-1 ms-4\">\r\n");
      out.write("                                                                                                                <h6 class=\"fs-lg-1 mb-1 text-uppercase\">Ainara Vergara</h6>\r\n");
      out.write("                                                                                                        </div>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                                <p class=\"mb-0 mt-4 fw-light lh-lg\">Nisi cumque in necessitatibus molestiae eaque excepturi ab. Laboriosam ipsam voluptatem voluptatibus labore quam nihil. Quasi occaecati quos ratione quia aut molestiae velit et.</p>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"carousel-item\" data-bs-interval=\"5000\">\r\n");
      out.write("                                                                <div class=\"row h-100 justify-content-center\">\r\n");
      out.write("                                                                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                                                                <div class=\"card h-100 shadow card-span p-3 bg-black\">\r\n");
      out.write("                                                                                        <div class=\"card-body\">\r\n");
      out.write("                                                                                                <div class=\"d-flex align-items-center\"><img class=\"img-fluid\" src=\"assets/img/gallery/smith.png\" width=\"80\" alt=\"testimonials\" />\r\n");
      out.write("                                                                                                        <div class=\"flex-1 ms-4\">\r\n");
      out.write("                                                                                                                <h6 class=\"fs-lg-1 mb-1 text-uppercase\">Niek Bove</h6>\r\n");
      out.write("                                                                                                        </div>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                                <p class=\"mb-0 mt-4 fw-light lh-lg\">Nisi cumque in necessitatibus molestiae eaque excepturi ab. Laboriosam ipsam voluptatem voluptatibus labore quam nihil. Quasi occaecati quos ratione quia aut molestiae velit et.</p>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                                                                <div class=\"card h-100 shadow card-span p-3 bg-black\">\r\n");
      out.write("                                                                                        <div class=\"card-body\">\r\n");
      out.write("                                                                                                <div class=\"d-flex align-items-center\"><img class=\"img-fluid\" src=\"assets/img/gallery/sandra-willims.png\" width=\"80\" alt=\"testimonials\" />\r\n");
      out.write("                                                                                                        <div class=\"flex-1 ms-4\">\r\n");
      out.write("                                                                                                                <h6 class=\"fs-lg-1 mb-1 text-uppercase\">Ainara Vergara</h6>\r\n");
      out.write("                                                                                                        </div>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                                <p class=\"mb-0 mt-4 fw-light lh-lg\">Nisi cumque in necessitatibus molestiae eaque excepturi ab. Laboriosam ipsam voluptatem voluptatibus labore quam nihil. Quasi occaecati quos ratione quia aut molestiae velit et.</p>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"carousel-item\">\r\n");
      out.write("                                                                <div class=\"row h-100 justify-content-center\">\r\n");
      out.write("                                                                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                                                                <div class=\"card h-100 shadow card-span p-3 bg-black\">\r\n");
      out.write("                                                                                        <div class=\"card-body\">\r\n");
      out.write("                                                                                                <div class=\"d-flex align-items-center\"><img class=\"img-fluid\" src=\"assets/img/gallery/smith.png\" width=\"80\" alt=\"testimonials\" />\r\n");
      out.write("                                                                                                        <div class=\"flex-1 ms-4\">\r\n");
      out.write("                                                                                                                <h6 class=\"fs-lg-1 mb-1 text-uppercase\">amanda smith</h6>\r\n");
      out.write("                                                                                                        </div>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                                <p class=\"mb-0 mt-4 fw-light lh-lg\">Nisi cumque in necessitatibus molestiae eaque excepturi ab. Laboriosam ipsam voluptatem voluptatibus labore quam nihil. Quasi occaecati quos ratione quia aut molestiae velit et.</p>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                                                                <div class=\"card h-100 shadow card-span p-3 bg-black\">\r\n");
      out.write("                                                                                        <div class=\"card-body\">\r\n");
      out.write("                                                                                                <div class=\"d-flex align-items-center\"><img class=\"img-fluid\" src=\"assets/img/gallery/sandra-willims.png\" width=\"80\" alt=\"testimonials\" />\r\n");
      out.write("                                                                                                        <div class=\"flex-1 ms-4\">\r\n");
      out.write("                                                                                                                <h6 class=\"fs-lg-1 mb-1 text-uppercase\">Ainara Vergara</h6>\r\n");
      out.write("                                                                                                        </div>\r\n");
      out.write("                                                                                                </div>\r\n");
      out.write("                                                                                                <p class=\"mb-0 mt-4 fw-light lh-lg\">Nisi cumque in necessitatibus molestiae eaque excepturi ab. Laboriosam ipsam voluptatem voluptatibus labore quam nihil. Quasi occaecati quos ratione quia aut molestiae velit et.</p>\r\n");
      out.write("                                                                                        </div>\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"row mt-5 flex-center\">\r\n");
      out.write("                                                        <div class=\"col-auto position-relative z-index-2\">\r\n");
      out.write("                                                                <ol class=\"carousel-indicators\">\r\n");
      out.write("                                                                        <li class=\"active mx-2\" data-bs-target=\"#carouselTestimonials\" data-bs-slide-to=\"0\"></li>\r\n");
      out.write("                                                                        <li class=\"mx-2\" data-bs-target=\"#carouselTestimonials\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("                                                                        <li class=\"mx-2\" data-bs-target=\"#carouselTestimonials\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("                                                                </ol>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- end of .container-->\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- <section> close ============================-->\r\n");
      out.write("        <!-- ============================================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ============================================-->\r\n");
      out.write("        <!-- <section> begin ============================-->\r\n");
      out.write("        ");
      out.write("<section class=\"py-0 pt-7\" id=\"contact\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-6 col-sm-4 col-xl-3 mb-3\">\r\n");
      out.write("        <h4 class=\"lh-lg fw-bold text-light\">WATCH</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-sm-4 col-xl-3 mb-3\">\r\n");
      out.write("        <h5 class=\"lh-lg fw-bold text-light\">MENU</h5>\r\n");
      out.write("        <ul class=\"list-unstyled mb-md-4 mb-lg-0\">\r\n");
      out.write("          <li class=\"lh-lg\"><a class=\"text-800 text-decoration-none text-uppercase fw-bold\" href=\"#!\">Shipping Info</a></li>\r\n");
      out.write("          <li class=\"lh-lg\"><a class=\"text-800 text-decoration-none text-uppercase fw-bold\" href=\"#!\">Refunds</a></li>\r\n");
      out.write("          <li class=\"lh-lg\"><a class=\"text-800 text-decoration-none text-uppercase fw-bold\" href=\"#!\">How to Order</a></li>\r\n");
      out.write("          <li class=\"lh-lg\"><a class=\"text-800 text-decoration-none text-uppercase fw-bold\" href=\"#!\">How to Track</a></li>\r\n");
      out.write("          <li class=\"lh-lg\"><a class=\"text-800 text-decoration-none text-uppercase fw-bold\" href=\"#!\">Size Guides</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-sm-4 col-xl-3 mb-3\">\r\n");
      out.write("        <h5 class=\"mb-5\"></h5>\r\n");
      out.write("        <ul class=\"list-unstyled mb-md-4 mb-lg-0\">\r\n");
      out.write("          <li class=\"lh-lg\"><a class=\"text-800 text-decoration-none text-uppercase fw-bold\" href=\"#!\">Contact Us</a></li>\r\n");
      out.write("          <li class=\"lh-lg\"><a class=\"text-800 text-decoration-none text-uppercase fw-bold\" href=\"#!\">my account</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-12 col-xl-3\">\r\n");
      out.write("        <h5 class=\"lh-lg fw-bold text-light text-uppercase\">Signup For our Latest News</h5>\r\n");
      out.write("        <div class=\"row input-group-icon mb-5\">\r\n");
      out.write("          <div class=\"col-12\">\r\n");
      out.write("            <form class=\"row row-cols-lg-auto g-0 align-items-center\">\r\n");
      out.write("              <div class=\"col-8 col-lg-9\">\r\n");
      out.write("                <label class=\"visually-hidden\" for=\"colFormLabel\">Username</label>\r\n");
      out.write("                <div class=\"input-group\">\r\n");
      out.write("                  <input class=\"rounded-end-0 form-control\" id=\"colFormLabel\" type=\"email\" placeholder=\"email address\" />\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-4 col-lg-3\">\r\n");
      out.write("                <button class=\"btn btn-primary rounded-start-0\" type=\"submit\">Submit</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"border-bottom border-700\"></div>\r\n");
      out.write("    <div class=\"row flex-center my-3\">\r\n");
      out.write("      <div class=\"col-md-6 order-1 order-md-0\">\r\n");
      out.write("        <p class=\"my-2 text-800 text-center text-md-start\"> Made with&nbsp;\r\n");
      out.write("          <svg class=\"bi bi-suit-heart-fill\" xmlns=\"http://www.w3.org/2000/svg\" width=\"15\" height=\"15\" fill=\"#EB6453\" viewBox=\"0 0 16 16\">\r\n");
      out.write("            <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"></path>\r\n");
      out.write("          </svg>&nbsp;by&nbsp;<a class=\"text-500\" href=\"https://themewagon.com/\" target=\"_blank\">ThemeWagon </a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-6\">\r\n");
      out.write("        <div class=\"text-center text-md-end\"><a href=\"#!\"><span class=\"me-4\" data-feather=\"facebook\"></span></a><a href=\"#!\"> <span class=\"me-4\" data-feather=\"instagram\"></span></a><a href=\"#!\"> <span class=\"me-4\" data-feather=\"youtube\"></span></a><a href=\"#!\"> <span class=\"me-4\" data-feather=\"twitter\"></span></a></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- end of .container-->\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("        <!-- <section> close ============================-->\r\n");
      out.write("        <!-- ============================================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<!-- ===============================================-->\r\n");
      out.write("<!--    End of Main Content-->\r\n");
      out.write("<!-- ===============================================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ===============================================-->\r\n");
      out.write("<!--    JavaScripts-->\r\n");
      out.write("<!-- ===============================================-->\r\n");
      out.write("<script src=\"vendors/@popperjs/popper.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/is/is.min.js\"></script>\r\n");
      out.write("<script src=\"vendors/feather-icons/feather.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("        feather.replace();\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"assets/js/theme.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;700&amp;display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
